/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author nifsi
 */
public class combobox extends javax.swing.JFrame {
    ArrayList<String>pesanan=new ArrayList<>();
    int totalSemua = 0;
    /**
     * Creates new form combobox
     */
    public combobox() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(44,44,44));

        
        makan_minum.removeAllItems();
        makan_minum.addItem("Makanan");
        makan_minum.addItem("Minuman");
        makan_minum.addItem("Snack");
        makan_minum.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        makan_minum = new javax.swing.JComboBox<>();
        Meja_field = new javax.swing.JTextField();
        pemesanan_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        pesan = new javax.swing.JButton();
        tambah_pesanan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 44, 44));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        makan_minum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        makan_minum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makan_minumActionPerformed(evt);
            }
        });

        Meja_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Meja_fieldActionPerformed(evt);
            }
        });

        pemesanan_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemesanan_fieldActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Warung Makan");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Meja:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama:");

        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_menu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                list_menuFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(list_menu);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kategori Menu:");

        pesan.setBackground(new java.awt.Color(111, 78, 55));
        pesan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesan.setForeground(new java.awt.Color(255, 255, 255));
        pesan.setText("Pesan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });

        tambah_pesanan.setBackground(new java.awt.Color(111, 78, 55));
        tambah_pesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tambah_pesanan.setForeground(new java.awt.Color(255, 255, 255));
        tambah_pesanan.setText("Tambah Pesanan ");
        tambah_pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_pesananActionPerformed(evt);
            }
        });

        hapus.setBackground(new java.awt.Color(111, 78, 55));
        hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Hapus Semua");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tambah_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Meja_field, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pemesanan_field, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(makan_minum, 0, 307, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Meja_field)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(pemesanan_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(makan_minum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah_pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Meja_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Meja_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Meja_fieldActionPerformed

    private void pemesanan_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesanan_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemesanan_fieldActionPerformed

    private void list_menuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_list_menuFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_list_menuFocusGained

    private void makan_minumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makan_minumActionPerformed
        if (makan_minum.getSelectedItem() == null) {
                return; // hentikan kalau kosong
    }

        String kategori = makan_minum.getSelectedItem().toString();
        if (kategori.equals("Makanan")) {
            list_menu.setListData(new String[]{
                "Nasi Goreng",
                "Mie Ayam",
                "Mie Ayam Bakso",
                "Bakso Arema",
                "Sate Ayam",
                "Sate Kelinci"
            });
        } 
        else if (kategori.equals("Minuman")) {
            list_menu.setListData(new String[]{
                "Jus Buah",
                "Air Mineral",
                "Teh Hot",
                "Teh Ice",
                "Kopi Americano Hot",
                "Kopi Americano Ice",
                "Coklat Hot",
                "Coklat Ice"
            });
        }
        else if (kategori.equals("Snack")) {
            list_menu.setListData(new String[]{
                "Pisang Goreng",
                "Kentang Goreng",
                "Pancong",
                "Risol Solo", 
            });
        }
    }//GEN-LAST:event_makan_minumActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
    String nomorMeja = Meja_field.getText();
    String namaPemesanan = pemesanan_field.getText();
    
    if (nomorMeja.isEmpty()){
        JOptionPane.showMessageDialog(this,"Nomor meja belum diisi!");
        Meja_field.requestFocus();
        return;
    }
    
    if (namaPemesanan.isEmpty()){
        JOptionPane.showMessageDialog(this, "Nama pemesan belum diisi!");
        pemesanan_field.requestFocus();
        return;
    }

    if (pesanan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Pesan menu dulu!");
        return;
    }
    int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin pesanan sudah lengkap?\nTidak ada tambahan pesanan lagi?",
            "Konfirmasi Pesanan",
            JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi == JOptionPane.NO_OPTION) {
        return; 
    }   
    String hasil="";
    for(String p:pesanan){
        hasil+=p+ "\n";
    }
    
    JOptionPane.showMessageDialog(this,
        "====STRUK PESANAN====\n"+
        "No Meja: " + nomorMeja +
        "\nPemesanan: " + namaPemesanan +
        "\n--------------------------\n"+hasil+
        "\n---------------------------\n"+
        "Total : Rp" + totalSemua);
    }//GEN-LAST:event_pesanActionPerformed

    private void tambah_pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_pesananActionPerformed
        String menu=list_menu.getSelectedValue();
        
        if(menu==null){
            JOptionPane.showMessageDialog(this, "Pesan menu dulu!");
            return;
        }
        
        String inputJumlah=JOptionPane.showInputDialog("Masukkan jumlah: ");
        if (inputJumlah == null) {
            return;
        }

        if (inputJumlah.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah tidak boleh kosong!");
            return;
        }
        
        int jumlah=Integer.parseInt(inputJumlah);
        int harga = 0;

        if(menu.equals("Nasi Goreng")) harga = 12000;
        else if(menu.equals("Mie Ayam")) harga = 8000;
        else if(menu.equals("Mie Ayam Bakso")) harga = 10000;
        else if(menu.equals("Bakso Arema")) harga = 9000;
        else if(menu.equals("Sate Ayam")) harga = 20000;
        else if(menu.equals("Sate Kelinci")) harga = 25000;
        else if(menu.equals("Jus Buah")) harga = 8000;
        else if(menu.equals("Air Mineral")) harga = 4000;
        else if(menu.equals("Teh Hot")) harga = 4000;
        else if(menu.equals("Teh Ice")) harga = 5000;
        else if(menu.equals("Kopi Americano Hot")) harga = 9000;
        else if(menu.equals("Kopi Americano Hot")) harga = 10000;
        else if(menu.equals("Coklat Hot")) harga = 10000;
        else if(menu.equals("Coklat Ice")) harga = 12000;

        int total = harga * jumlah;
        totalSemua += total;

        pesanan.add(menu + " (" + jumlah + " porsi) = Rp" + total);
        JOptionPane.showMessageDialog(this, "Ditambahan");
    }//GEN-LAST:event_tambah_pesananActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed

        int konfirmasi=JOptionPane.showConfirmDialog(
        this,
                "Yakin hapus semua pesanan?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );
        if (konfirmasi ==JOptionPane.YES_OPTION){
            pesanan.clear();
            
            JOptionPane.showMessageDialog(this,"Semua pesanan dihapus!");
            Meja_field.setText("");
            pemesanan_field.setText("");
            list_menu.clearSelection();
        }
        else{
            return;
        }
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(combobox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new combobox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Meja_field;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JComboBox<String> makan_minum;
    private javax.swing.JTextField pemesanan_field;
    private javax.swing.JButton pesan;
    private javax.swing.JButton tambah_pesanan;
    // End of variables declaration//GEN-END:variables
}
